// Generated by gencpp from file service_client_test/intsum.msg
// DO NOT EDIT!


#ifndef SERVICE_CLIENT_TEST_MESSAGE_INTSUM_H
#define SERVICE_CLIENT_TEST_MESSAGE_INTSUM_H

#include <ros/service_traits.h>


#include <service_client_test/intsumRequest.h>
#include <service_client_test/intsumResponse.h>


namespace service_client_test
{

struct intsum
{

typedef intsumRequest Request;
typedef intsumResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct intsum
} // namespace service_client_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_client_test::intsum > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::service_client_test::intsum&) { return value(); }
};

template<>
struct DataType< ::service_client_test::intsum > {
  static const char* value()
  {
    return "service_client_test/intsum";
  }

  static const char* value(const ::service_client_test::intsum&) { return value(); }
};


// service_traits::MD5Sum< ::service_client_test::intsumRequest> should match
// service_traits::MD5Sum< ::service_client_test::intsum >
template<>
struct MD5Sum< ::service_client_test::intsumRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service_client_test::intsum >::value();
  }
  static const char* value(const ::service_client_test::intsumRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_client_test::intsumRequest> should match
// service_traits::DataType< ::service_client_test::intsum >
template<>
struct DataType< ::service_client_test::intsumRequest>
{
  static const char* value()
  {
    return DataType< ::service_client_test::intsum >::value();
  }
  static const char* value(const ::service_client_test::intsumRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_client_test::intsumResponse> should match
// service_traits::MD5Sum< ::service_client_test::intsum >
template<>
struct MD5Sum< ::service_client_test::intsumResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service_client_test::intsum >::value();
  }
  static const char* value(const ::service_client_test::intsumResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_client_test::intsumResponse> should match
// service_traits::DataType< ::service_client_test::intsum >
template<>
struct DataType< ::service_client_test::intsumResponse>
{
  static const char* value()
  {
    return DataType< ::service_client_test::intsum >::value();
  }
  static const char* value(const ::service_client_test::intsumResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_CLIENT_TEST_MESSAGE_INTSUM_H
