// Generated by gencpp from file service_client_test/intsumResponse.msg
// DO NOT EDIT!


#ifndef SERVICE_CLIENT_TEST_MESSAGE_INTSUMRESPONSE_H
#define SERVICE_CLIENT_TEST_MESSAGE_INTSUMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace service_client_test
{
template <class ContainerAllocator>
struct intsumResponse_
{
  typedef intsumResponse_<ContainerAllocator> Type;

  intsumResponse_()
    : sum(0)  {
    }
  intsumResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int32_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::service_client_test::intsumResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::service_client_test::intsumResponse_<ContainerAllocator> const> ConstPtr;

}; // struct intsumResponse_

typedef ::service_client_test::intsumResponse_<std::allocator<void> > intsumResponse;

typedef boost::shared_ptr< ::service_client_test::intsumResponse > intsumResponsePtr;
typedef boost::shared_ptr< ::service_client_test::intsumResponse const> intsumResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::service_client_test::intsumResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::service_client_test::intsumResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::service_client_test::intsumResponse_<ContainerAllocator1> & lhs, const ::service_client_test::intsumResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::service_client_test::intsumResponse_<ContainerAllocator1> & lhs, const ::service_client_test::intsumResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace service_client_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::service_client_test::intsumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::service_client_test::intsumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_client_test::intsumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_client_test::intsumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_client_test::intsumResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_client_test::intsumResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::service_client_test::intsumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ba699c25c9418c0366f3595c0c8e8ec";
  }

  static const char* value(const ::service_client_test::intsumResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ba699c25c9418c0ULL;
  static const uint64_t static_value2 = 0x366f3595c0c8e8ecULL;
};

template<class ContainerAllocator>
struct DataType< ::service_client_test::intsumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "service_client_test/intsumResponse";
  }

  static const char* value(const ::service_client_test::intsumResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::service_client_test::intsumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 响应\n"
"int32 sum\n"
;
  }

  static const char* value(const ::service_client_test::intsumResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::service_client_test::intsumResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct intsumResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::service_client_test::intsumResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::service_client_test::intsumResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVICE_CLIENT_TEST_MESSAGE_INTSUMRESPONSE_H
